### ISSUE TITLE
API randomly responds in different languages

### ISSUE THREAD

**Issue by sebsebmc** [dealloc/helldivers2-api#1]
The text for the campaign assignment messages occasionally responds in different languages.

**Comment by dealloc** [comment]
hi @sebsebmc some folks on Reddit caught on to this as well (you can view the thread [here](https://www.reddit.com/r/Helldivers/comments/1b11wkw/comment/kslb5xu/?context=3)), we haven't been able to figure out why/how it determines the language to output.

Ideally we'd find a way to reliably have it output messages in multiple languages so this API can offer translations in available langauges but at the moment it's a bit random

**Comment by superintendent2521** [comment]
is it by chance the way that its deployed on fly.io and the backend api uses ip location for Language?

**Comment by dealloc** [comment]
I doubt it, as I've seen it switch between languages on my own device (which I assume doesn't bounce it's IP over the globe)

it's seemingly random

**Comment by superintendent2521** [comment]
Then i would be wrong

**Comment by sebsebmc** [comment]
So this API is just reflecting what you recently retrieved? Would it be possible to try and drop responses that aren't in English and fetch again?

**Comment by dealloc** [comment]
> So this API is just reflecting what you recently retrieved? Would it be possible to try and drop responses that aren't in English and fetch again?

Theoretically yes, I've toyed with the same idea.
The problem is how I would detect a language that is _not_ English:
things like Chinese, Russian, ... are easy as they use non-latin character sets, but Italian, French, German etc are a lot harder as I would almost have to start checking if the message contains "known" keywords.
An alternative would be to use the "title" as it seems to fall back to a sort of identifier when not returning English, however I've already seen English text with identifier titles so that's not entirely reliable either I'm afraid.

I'm keeping this issue open since I definitely want to tackle this, I just haven't found a 'proper' way to clean it up yet.

**Comment by MrFlou** [comment]
I do not know if this is the way to fix it for the method currently used, but locally for me I just add 
`-H "Accept-Language: en-US,en;q=0.5"` to my curl request, then I would always get English back. Maybe adding a header with the wanted language? (this just sprung to mind, haven't checked if you already are doing something similar.)

**Comment by Kejax** [comment]
`Accepted-Language: en-US` works, as well as `de-DE`, `es-ES` etc.

**Comment by Kejax** [comment]
ru-RU
fr-FR
it-IT
pl-PL
All of them are tested

**Comment by dealloc** [comment]
the API will now respond with all available languages for `message` rather than a plain string when returning global events
