### ISSUE TITLE
"sector" field missing from OpenApi

### ISSUE THREAD

**Issue by juanlubf** [dealloc/helldivers2-api#16]
The field "sector" is not defined in PlanetSchema, yet it is returned from the API. 
Besides, the field seems to be returning sometimes a name, and sometimes, a number (in String format).

**Comment by juanlubf** [comment]
@dealloc Thanks. Seems like I'll have to wait a bit until I can filter planets by sector. Any idea or workaround about this for now?

**Comment by dealloc** [comment]
I'm afraid not, the main reason they haven't been fully mapped is because when I started I noticed that some planets report being in different sectors while they are in the same sector in game.

So even if I just returned the underlying ID as the API gave them (so split sector name and ID in separate fields) it wouldn't be consistent regardless

**Comment by juanlubf** [comment]
Ok, thanks for the info. I hope this changes in the near future!
